### ISSUE TITLE
ERROR: Invalid DSL JSON data on Danger Swift 0.7.2

### ISSUE THREAD

**Issue by erikstrottmann** [danger/swift#133]
Since updating from 0.7.1 to 0.7.2, Danger Swift is failing every time on our CircleCI builds.

Danger is being installed through Homebrew (`brew install danger/tap/danger-swift`), so we can’t easily specify which version to use.

Output of `danger process danger-swift` with **Danger Swift 0.7.2** and Danger JS 6.1.8:
```
^D^DERROR: Invalid DSL JSON data

Failing the build, there is 1 fail.
Feedback: https://github.com/clutter/clutter-ios-wms/pull/1110#issuecomment-443370291
Exited with code 1
```

Compared to the output of `danger process danger-swift` with **Danger Swift 0.7.1**, still using Danger JS 6.1.8:
```
Found no issues or messages from Danger. Removing any existing messages on GitHub.
```

This appears to be unrelated to #131.

**Comment by f-meloni** [comment]
The solution should be update danger js to 6.1.8

**Comment by f-meloni** [comment]
Ok I just saw in your message that you are currently to that version...
Mmmm that looks odd then

**Comment by f-meloni** [comment]
Could you try to install danger js via npm instead of brew?

**Comment by erikstrottmann** [comment]
@f-meloni, I tried installing Danger JS via Yarn, which also didn’t work.

The relevant part of my `.circleci.config.yml`:
```
    steps:
      - checkout
      - run: yarn global add danger
      - run: brew install --ignore-dependencies danger/tap/danger-swift
      - run: brew install swiftlint
      - run:
          name: Danger
          command: danger process danger-swift
```

`yarn global add danger` output, installs Danger JS 6.1.9 (not 6.1.8) via Yarn 1.12.1:
```
yarn global v1.12.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Installed "danger@6.1.9" with binaries:
      - danger
      - danger-js
      - danger-pr
      - danger-runner
      - danger-process
      - danger-ci
      - danger-init
      - danger-local
      - danger-reset-status
✨  Done in 7.16s.
```

`brew install --ignore-dependencies danger/tap/danger-swift` output, installs Danger Swift 0.7.3 (not 0.7.2):
```
==> Tapping danger/tap
Cloning into '/usr/local/Homebrew/Library/Taps/danger/homebrew-tap'...
remote: Enumerating objects: 6, done.        
remote: Counting objects: 100% (6/6), done.        
remote: Compressing objects: 100% (6/6), done.        
remote: Total 6 (delta 0), reused 1 (delta 0), pack-reused 0        
Receiving objects: 100% (6/6), done.
Tapped 2 formulae (29 files, 28KB).
==> Installing danger-swift from danger/tap
==> Downloading https://github.com/danger/danger-swift/archive/0.7.3.tar.gz
==> Downloading from https://codeload.github.com/danger/swift/tar.gz/0.7.3

######################################################################## 100.0%
==> make install PREFIX=/usr/local/Cellar/danger-swift/0.7.3
🍺  /usr/local/Cellar/danger-swift/0.7.3: 17 files, 12.3MB, built in 1 minute 41 seconds
```

And again, `danger process danger-swift` output:
```
^D^DERROR: Invalid DSL JSON data
```

**Comment by erikstrottmann** [comment]
That fixed it, thanks!

**Comment by erikstrottmann** [comment]
https://danger.systems/js/swift.html#how-do-i-use-it still recommends `danger process danger-swift`. I’d be happy to submit a PR to update that. Where is that page’s source hosted?

**Comment by f-meloni** [comment]
@erikstrottmann the website is hosted here https://gitlab.com/danger-systems/danger.systems
I don't know much about it, probably @orta can give you some advices about how to modify the website

**Comment by orta** [comment]
Heyo, that's in https://gitlab.com/danger-systems/danger.systems/blob/master/static/source/js/swift.html.md

We've been blocked by  https://github.com/danger/swift/issues/97 for longer than I would have liked and will eventually replace that with docs I this repo
