### ISSUE TITLE
GitLab CI support

### ISSUE THREAD

**Issue by maks-g** [danger/swift#199]
Hi!

Any plans to support GitLab CI ?

**Comment by f-meloni** [comment]
Hi, `danger-swift` uses `danger-js` for get data and post on PRs, but I don't think there are any plans for GitLab support there :(

**Comment by maks-g** [comment]
It's sad :(

Do you know a reason why GitLab is ignored?

**Comment by f-meloni** [comment]
I think is more that no one ever did the implementation of it :)
Danger mainly supports GitHub AFAIK, but people can add and maintain implementation for other platforms if they want (like BitbucketServer)

**Comment by orta** [comment]
If you want to give it a shot: https://github.com/danger/danger-js/issues/396
