### ISSUE TITLE
[feature request] Possibility to specify custom path for Dangerfile.swift from command line?

### ISSUE THREAD

**Issue by peacemoon** [danger/swift#212]
We have an app project with different targets. Currently we run Danger after checkout to cover changes in all targets, after this step we stash and test all targets parallel on different jenkins slaves. We want to use `danger-swift-coverage` to gather coverage information of each targets. 
We are thinking of split our `Dangerfile` into 2 steps, one will be run before test, one after test for code coverage. 
It seems that danger-swift can't supply custom  `Dangerfile` path as parameter at this moment which prevent us to do what we want.
It would be a nice addition.

Thank you for great tool though.

**Comment by f-meloni** [comment]
You can use the `—dangerfile` option to specify the danger file path, I also suggest you to use two different ids (`—id` option).
That will make danger create two different comments, one for each run, instead of making it override always the same

**Comment by peacemoon** [comment]
<img width="1393" alt="Screenshot 2019-03-19 at 15 54 03" src="https://user-images.githubusercontent.com/478757/54615954-40249a80-4a5f-11e9-969a-540395f78841.png">

huhm, doesn't seem to work for me

**Comment by f-meloni** [comment]
Try `danger-swift local —dangerfile Dangerfile.swift`, it should work :)

**Comment by peacemoon** [comment]
Thanks, it works

**Comment by peacemoon** [comment]
For anyone found this via google
Just take a look at the source code https://github.com/danger/swift/blob/35c672e1809fa1d2b4554c54b0b2885788e6dfeb/Sources/RunnerLib/DangerfileArgumentsPath.swift
The command should be
`danger-swift local —dangerfile Dangerfile.swift`
