### ISSUE TITLE
Error running locally: the installed danger-js version is below the minimum supported version

### ISSUE THREAD

**Issue by thedavidharris** [danger/swift#220]
When running `swift run danger-swift pr { % url % }`, get the message:
```
ERROR: the installed danger-js version is below the minimum supported version
Current version = 5.16.1
Minimum supported version = 6.1.6
```

This is after running npm install -g danger, and verifying that  `npm list -g | grep danger` shows `danger@7.1.0`

Been a while since I did anything in the npm ecosystem so not sure if I've got something setup wrong.

**Comment by f-meloni** [comment]
Is it possible that you have also danger ruby installed on your machine?

**Comment by thedavidharris** [comment]
Yep figured that out right after posting this. It might be worth including in the docs to check that `which danger` points to danger-js specifically.

**Comment by jsmi1417-ford** [comment]
we experienced this issue too. 
```which danger
.../.rvm/gems/ruby-2.5.1/bin/danger
```
and we had old danger gem installed
It looks like to use latest danger via brew we need to uninstall old danger gem:
`gem uninstall danger`

**Comment by ashfurrow** [comment]
Also just ran into this, thank you for the recommendation to check `which danger` 👍
