### ISSUE TITLE
`swift build` fails compiling DangerDSL.swift

### ISSUE THREAD

**Issue by dgcoffman** [danger/swift#221]
I'm attempting to following [the getting started guide](https://danger.systems/swift/guides/getting_started.html#swift-pm) by running `swift build` and it fails with following output:
```
/.build/checkouts/swift/Sources/Danger/DangerDSL.swift:61:24: 
error: immutable value 'self.github' may only be initialized once
            github.api = Octokit(config)
                       ^
/.build/checkouts/swift/Sources/Danger/DangerDSL.swift:16:12: 
note: change 'let' to 'var' to make it mutable
    public let github: GitHub!
           ^~~
           var
```

About me
```
swift -version
Apple Swift version 5.0 (swiftlang-1001.0.69.5 clang-1001.0.46.3)

swift package tools-version
5.0.0

System Version: macOS 10.14.4
```

Package.swift
``` swift
// swift-tools-version:5.0

import PackageDescription

let package = Package(
    name: "Eigen",
    dependencies: [
        .package(url: "https://github.com/danger/swift.git", from: "0.8.0")
    ],
    targets: [
        // This is just an arbitrary Swift file in our app, that has
        // no dependencies outside of Foundation, the dependencies section
        // ensures that the library for Danger gets build also.
        .target(name: "eigen", dependencies: ["Danger"], path: "", sources: ["DangerRequiresThis.swift"]),
    ]
)
``` 
(this example Package.swift was introduced recently in [this PR](https://gitlab.com/danger-systems/danger.systems/commit/d628fef8ca0f3e72aa36e6fd511563f2844f8d89#6b0f4e17f37f5ea51f169e6e1eaa04a0151b17d1_0_38) by @orta)

DangerRequiresThis.swift
```
import Foundation
```
___

I hand-edited DangerDSL.swift to make `github` a `var`, which let `swift build` complete with output 
```
[3/3] Compiling Swift Module 'eigen' (1 sources)
```

but `swift run danger edit` now yields `error: no executable product named 'danger'`

Any ideas?

**Comment by dgcoffman** [comment]
I see there are apparently newer instructions in the README https://github.com/danger/swift/blob/master/README.md#swift-package-manager-more-performant

I then tried Package.swift
``` swift
// swift-tools-version:5.0

import PackageDescription

let package = Package(
    name: "Stopwatch",
    products: [
        .library(name: "DangerDeps[Product name (optional)]", type: .dynamic, targets: ["DangerDependencies"]),
    ],
    dependencies: [
        .package(url: "https://github.com/danger/swift.git", from: "1.5.2"),
    ],
    targets: [
        .target(name: "DangerDependencies", dependencies: ["Danger", "DangerPlugin"], path: ""),
    ]
)
```

with this config, `swift build` creates output 
```
error: target at `MyTarget' contains mixed language source files; feature not supported
```

**Comment by f-meloni** [comment]
Unfortunately the last thing is a marathon issue :(

**Comment by f-meloni** [comment]
Ps I think the reason of the first crash was you were using an old version of Danger that was not supporting swift 5.0 :)

**Comment by dgcoffman** [comment]
> I think the reason of the first crash was you were using an old version of Danger that was not supporting swift 5.0 :)

Right, the problem there is that the [getting started guide] says to do that https://danger.systems/swift/guides/getting_started.html#swift-pm

**Comment by dgcoffman** [comment]
> Unfortunately the last thing is a marathon issue :(

Looks like the fix is in their master https://github.com/JohnSundell/Marathon/commit/128e7387b82168c1d3fe86b85ba4bf891387a47f

**Comment by f-meloni** [comment]
The swift 5.0 initial support (just to make it compile) was introduced in the version 1.3.0 if I remember correctly.
https://github.com/danger/swift/pull/191
But yes the documentation is still at before we moved to 1.0.0, then the max version you can get with the README config is one before 1.0.0 😁

**Comment by f-meloni** [comment]
> Looks like the fix is in their master JohnSundell/Marathon@128e738
 
Nice, but I think he didn't release it yet, because on my branch I updated the dependencies few days ago and didn't see any new Marathon version.
Best option for me would be ask him if is possible to get a marathon release, otherwise I can point master, or better the commit, but I would like to avoid it

**Comment by dgcoffman** [comment]
I'll just come back and try again once John cuts a Marathon release with the fix in it 👍 

thank you!

**Comment by f-meloni** [comment]
Anyway I went to update the README and I realised that the README is actually correct, it says `from: "1.0.0"`, but you had `from: 0.8.0`

**Comment by f-meloni** [comment]
Was there any additional thing you had to change to make it work that I should add to the README?

**Comment by dgcoffman** [comment]
> Anyway I went to update the README and I realised that the README is actually correct, it says from: "1.0.0", but you had from: 0.8.0

0.8.0 is in https://danger.systems/swift/guides/getting_started.html#swift-pm

**Comment by f-meloni** [comment]
Oh ok we need to update the website then!
Thank you :)

**Comment by dgcoffman** [comment]
> Was there any additional thing you had to change to make it work that I should add to the README?

Grant write permissions on the Cache directory

Delete
```
         // Danger Plugins
        .package(url: "https://github.com/username/DangerPlugin.git", from: "0.1.0") // dev
        ...
```

Add a name property to Package.swift

Add sources to the .target in Package.swift

I'd recommend providing a Package.swift file that works verbatim.

**Comment by f-meloni** [comment]
mmmm few notes

if I delete 
```
.package(url: "https://github.com/username/DangerPlugin.git", from: "0.1.0") // dev
```
It actually removes the example on how import an external SPM plugin on Danger.
I can add some links to example Dangerfiles, like the one you found.

The cache directory should be on your `~` folder, then you should have access to it

**Comment by f-meloni** [comment]
Closing because Marathon is updated and the doc in the website was updated ad well
