### ISSUE TITLE
SwiftLint JSON deserialization fails

### ISSUE THREAD

**Issue by thedavidharris** [danger/swift#222]
Partly logging this so I don't forget it, but just calling SwiftLint.lint() in the Dangerfile.swift is giving this output:

```
Error deserializing SwiftLint JSON response (�(B�[m[
{
"character" : null,
"file" : "File0.swift",
"line" : 63,
"reason" : "Line should be 160 characters or less: currently 401 characters",
"rule_id" : "line_length",
"severity" : "Error",
"type" : "Line Length"
},
{
"character" : 9,
"file" : "File1.swift",
"line" : 16,
"reason" : "A fatalError call should have a message.",
"rule_id" : "fatal_error_message",
"severity" : "Warning",
"type" : "Fatal Error Message"
}
]
): dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.})))
```

**Comment by f-meloni** [comment]
I suppose the problem is the `(�(B�[m` at the beginning of the response.
It remembers me https://github.com/radex/SwiftyUserDefaults/pull/181 that has a similar problem

**Comment by thedavidharris** [comment]
Seems like that was fixed by downgrading to Ruby 2.5.1 in that case?

**Comment by f-meloni** [comment]
Yes, but it worked because downgrading ruby, or better remove the `rvm install` removed the line 
`Using /Users/travis/.rvm/gems/ruby-2.5.1` from the swiftlint output.
Because `Swiftlint` uses `Codable` on the command output, then if the command contains something at the beginning it fails

**Comment by thedavidharris** [comment]
Right, I guess I've having trouble understanding why the unicode characters are appearing at the beginning of the response that would cause this in the first place. I'm just running this locally for now, env is all set to UTF8.

**Comment by f-meloni** [comment]
could it be something related to the shell you are using?

**Comment by thedavidharris** [comment]
It definitely is, as it works fine on our CI machines but it's just local. I can't tell what's tripped it though, will update if I figure it out.

**Comment by thedavidharris** [comment]
Going to close this as it's definitely a local terminal issue, although I haven't been able to figure out why

**Comment by mendesbarreto** [comment]
Hi guys, I am having the same issue with my Github Actons, someone found some solution?
