### ISSUE TITLE
Bitrise integración always fails

### ISSUE THREAD

**Issue by cerezo074** [danger/swift#243]
Hi, I've been working in the integration with bitrise just for run SwiftLint and get the comments on my prs. I followed the guide from your page and I added a step on my workflow to run the next sh script.

`
#!/usr/bin/env bash
set -ex

npm install -g danger
swift build
swift run danger-swift ci
`

The first command is installed because npm comes by default, but the second fails and log this error:

**swift build
error: root manifest not found**

I suppose this is done by the current path because it doesn't get Package.swift file. I am not an expert with my CI may be you can give me a better idea in, what do I need to do? or what is missing?.

Thank so much.

**Comment by f-meloni** [comment]
`swift build` is not related to Danger.
The reason is that in your root folder there is probably not a `Package.swift`.
Are you installing Danger via SPM? If so you should have your `Package.swift` in the root of the project.

**Comment by cerezo074** [comment]
Thanks for your answer @f-meloni.

I modified the path for look up on my CI and I think it could get the file and install danger through SPM, but now when it tries to reach the pr it fails with a 404 status code. When  **swift run danger-swift ci** command is running. 

`+ swift build
Fetching https://github.com/danger/swift.git
Fetching https://github.com/shibapm/Logger
Fetching https://github.com/nerdishbynature/octokit.swift
Fetching https://github.com/JohnSundell/Marathon
Fetching https://github.com/JohnSundell/Files.git
Fetching https://github.com/JohnSundell/Require.git
Fetching https://github.com/JohnSundell/ShellOut.git
Fetching https://github.com/JohnSundell/Releases.git
Fetching https://github.com/nerdishbynature/RequestKit.git
Completed resolution in 4.49s
Cloning https://github.com/JohnSundell/Releases.git
Resolving https://github.com/JohnSundell/Releases.git at 4.0.0
Cloning https://github.com/nerdishbynature/RequestKit.git
Resolving https://github.com/nerdishbynature/RequestKit.git at 2.3.0
Cloning https://github.com/JohnSundell/ShellOut.git
Resolving https://github.com/JohnSundell/ShellOut.git at 2.2.0
Cloning https://github.com/shibapm/Logger
Resolving https://github.com/shibapm/Logger at 0.2.3
Cloning https://github.com/JohnSundell/Require.git
Resolving https://github.com/JohnSundell/Require.git at 2.0.1
Cloning https://github.com/JohnSundell/Marathon
Resolving https://github.com/JohnSundell/Marathon at 3.2.0
Cloning https://github.com/nerdishbynature/octokit.swift
Resolving https://github.com/nerdishbynature/octokit.swift at 0.9.0
Cloning https://github.com/JohnSundell/Files.git
Resolving https://github.com/JohnSundell/Files.git at 2.3.0
Cloning https://github.com/danger/swift.git
Resolving https://github.com/danger/swift.git at 1.5.6
Compile Swift Module 'DangerShellExecutor' (1 sources)
Compile Swift Module 'RequestKit' (3 sources)
Compile Swift Module 'Logger' (1 sources)
Compile Swift Module 'OctoKit' (14 sources)
Compile Swift Module 'Danger' (15 sources)
Linking ./.build/x86_64-apple-macosx10.10/debug/libDanger.dylib
Compile Swift Module 'Example_Project' (1 sources)

+ swift run danger-swift ci
Compile Swift Module 'ShellOut' (1 sources)
Compile Swift Module 'Files' (1 sources)
Compile Swift Module 'Require' (1 sources)
Compile Swift Module 'RunnerLib' (14 sources)
Compile Swift Module 'Releases' (4 sources)
Compile Swift Module 'MarathonCore' (29 sources)
Compile Swift Module 'Runner' (6 sources)
Linking ./.build/x86_64-apple-macosx10.10/debug/danger-swift
**Request failed [404]: https://bitbucket.org/rest/api/1.0/abccompany/exampleprojectios/pull-requests/543/changes?start=0**
`                                                                      |

FYI The URL is invalid(i 've modified it just for illustrating), but I tried to put the host for the env variable on Bitrise but it doesn't work. 

DANGER_BITBUCKETSERVER_HOST = "https://bitbucket.org/abccompany/exampleprojectios

Am not sure if I did it well, any aid will be appreciated. Thanks so much.

**Comment by f-meloni** [comment]
I can not help you much with that, the 404 saya that the PR is not found, then probably the `DANGER_BITBUCKETSERVER_HOST` is wrong.
Notice that `DANGER_BITBUCKETSERVER_HOST` for `https://company-bitbucket.com/projects/project/repos/repo` should be `https://company-bitbucket.com`

**Comment by cerezo074** [comment]
Yes, I understand the status code but is very weird that the final URL that is generated for the repository host has an invalid path(api/1.0). This time I modified the host in the same way that bitbucket gives you to clone it(from the home page of your repo) https://bitbucket.org/abccompany/exampleprojectios.git but the outcome is the same even I cloned that and it works.

 The URL of the repo doesn't start with the hostname of my company, instead, it is moved to the path.

**Comment by f-meloni** [comment]
api/1.0 is not an invalid path, is the version 1.0 of this https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D/%7Brepo_slug%7D/issues/%7Bissue_id%7D/changes
But Bitbucket is not supported by Danger, only Bitbucket Server is.

**Comment by cerezo074** [comment]
Thanks for your information. I will be pending for this feature.
