### ISSUE TITLE
1 fail every time

### ISSUE THREAD

**Issue by meteora8888** [danger/swift#245]
Launching Danger Swift local (v1.5.6)
Finding out where the danger executable is
Running: /usr/local/bin/danger local --process danger-swift --passURLForDSL 
  danger:localGetDiff > git diff master...HEAD +0ms
  danger:process_runner Debug mode on for Danger v8.0.0 +0ms
  danger:process_runner Starting sub-process run +0ms
  danger:localGetDiff > git log master...HEAD --pretty=format:{ "sha": "%H", "parents": "%p", "author": {"name": "%an", "email": "%ae", "date": "%ai" }, "committer": {"name": "%cn", "email": "%ce", "date": "%ci" }, "message": "%f"}, +0ms
  danger:process_runner {
  danger:process_runner   dangerJSONDSL: {
  danger:process_runner     git: {
  danger:process_runner       fileMatch: [Function],
  danger:process_runner       modified_files: [Array],
  danger:process_runner       created_files: [],
  danger:process_runner       deleted_files: [],
  danger:process_runner       commits: [Array],
  danger:process_runner       diffForFile: [Function: diffForFile],
  danger:process_runner       structuredDiffForFile: [Function: structuredDiffForFile],
  danger:process_runner       JSONPatchForFile: [Function: JSONPatchForFile],
  danger:process_runner       JSONDiffForFile: [Function: JSONDiffForFile],
  danger:process_runner       linesOfCode: [Function: linesOfCode]
  danger:process_runner     },
  danger:process_runner     github: null,
  danger:process_runner     settings: { github: [Object], cliArgs: [Object] }
  danger:process_runner   }
  danger:process_runner } +23ms
  danger:process_runner Preparing to run: danger-swift +3ms
  danger:runDangerSubprocess Running sub-process: danger-swift -  +0ms
  danger:runDangerSubprocess Started passing in STDIN via the URL: danger://dsl//var/folders/5f/l_171f252xq69s5vkgv44tw80000gn/T/danger-dsl.json +5ms
  danger:runDangerSubprocess Passed DSL in via STDIN +1ms
Ran with: /var/folders/5f/l_171f252xq69s5vkgv44tw80000gn/T/_tmp_dangerfile.swift /var/folders/5f/l_171f252xq69s5vkgv44tw80000gn/T/danger-dsl.json /var/folders/5f/l_171f252xq69s5vkgv44tw80000gn/T/danger-response.json
Decoding the DSL into Swift types
Setting up to dump results
Sending results back to Danger

  danger:runDangerSubprocess Got JSON URL from STDOUT, results are at: 
  danger:runDangerSubprocess danger-results://var/folders/5f/l_171f252xq69s5vkgv44tw80000gn/T/danger-response.json +1s
Got URL for JSON: /var/folders/5f/l_171f252xq69s5vkgv44tw80000gn/T/danger-dsl.json
Created a temporary file for the Dangerfile DSL at: /var/folders/5f/l_171f252xq69s5vkgv44tw80000gn/T/danger-dsl.json
Running Dangerfile at: Dangerfile.swift
Preparing to compile
Running: /usr/bin/swiftc --driver-mode=swift -L /usr/local/lib/danger -I /usr/local/lib/danger -lDanger /var/folders/5f/l_171f252xq69s5vkgv44tw80000gn/T/_tmp_dangerfile.swift /var/folders/5f/l_171f252xq69s5vkgv44tw80000gn/T/danger-dsl.json /var/folders/5f/l_171f252xq69s5vkgv44tw80000gn/T/danger-response.json
Completed evaluation
Saving and storing the results at /var/folders/5f/l_171f252xq69s5vkgv44tw80000gn/T/danger-response.json

  danger:runDangerSubprocess child process exited with code 0 +4ms
  danger:jsonToDSL Creating pr DSL from JSON +0ms
  danger:localGetDiff > git diff master...HEAD +1s
  danger:localGetDiff > git log master...HEAD --pretty=format:{ "sha": "%H", "parents": "%p", "author": {"name": "%an", "email": "%ae", "date": "%ai" }, "committer": {"name": "%cn", "email": "%ce", "date": "%ci" }, "message": "%f"}, +1s
  danger:executor Got results back: {
  messages: [ { message: 'Highlight something in the table' } ],
  markdowns: [ { message: 'Make sure not to ignore warnings!' } ],
  meta: {
    runtimeHref: 'https://danger.systems/swift',
    runtimeName: 'Danger Swift'
  },
  fails: [ { message: 'Something that must be changed' } ],
  warnings: [
    {
      message: 'Something pretty bad, but not important enough to fail the build'
    }
  ]
} +0ms
  danger:executor Evaluator settings {
  stdoutOnly: true,
  verbose: undefined,
  jsonOnly: false,
  dangerID: 'Danger',
  passURLForDSL: true,
  disableGitHubChecksSupport: true,
  failOnErrors: undefined
} +1ms
  danger:executor Writing to STDOUT: {
  messages: [ { message: 'Highlight something in the table' } ],
  markdowns: [ { message: 'Make sure not to ignore warnings!' } ],
  meta: {
    runtimeHref: 'https://danger.systems/swift',
    runtimeName: 'Danger Swift'
  },
  fails: [ { message: 'Something that must be changed' } ],
  warnings: [
    {
      message: 'Something pretty bad, but not important enough to fail the build'
    }
  ]
} +1ms
Danger: ⅹ Failing the build, there is 1 fail.
## Failures
Something that must be changed
## Warnings
Something pretty bad, but not important enough to fail the build
## Messages
Highlight something in the table
## Markdowns
Make sure not to ignore warnings!

No clue why it always fails. Tried also with travis but no change 

Worker information
hostname: 4cc4696b-82bf-43c5-80fd-d9366ecb5907@1.worker-com-7dbdb678b6-qspll.macstadium-prod-2
version: v6.2.0 https://github.com/travis-ci/worker/tree/5e5476e01646095f48eec13196fdb3faf8f5cbf7
instance: 049c9c3d-809e-4dbe-9b2e-14ad4b8a2ec4 travis-ci-macos10.13-xcode10.1-1540999528 (via amqp)
startup: 1m4.813012377s
nvm is not compatible with the npm config "prefix" option: currently set to "/usr/local"
Run `npm config delete prefix` or `nvm use --delete-prefix v10.13.0 --silent` to unset it.
Build system information
Build language: ruby
Build id: 114976069
Job id: 206823322
Runtime kernel version: 17.7.0
travis-build version: 9f4eb462c
Build image provisioning date and time
Wed Oct 31 18:27:04 GMT 2018
Operating System Details
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G65
Git version
git version 2.19.1
bash version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)
Copyright (C) 2007 Free Software Foundation, Inc.
GCC version
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
LLVM version
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
Pre-installed Ruby versions
ruby-2.3.5
ruby-2.4.5
Pre-installed Node.js versions
v10.13.0
v4.9.1
v5.12.0
v6.14.4
v8.12.0
mvn -version
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z)
Maven home: /usr/local/Cellar/maven/3.5.4/libexec
Java version: 11.0.1, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/openjdk-11.0.1.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.6", arch: "x86_64", family: "mac"
Uninstalled oclint to prevent interference with other packages.
If you need oclint, you must explicitly install it.
git.checkout
0.43s$ git clone --depth=50 https://github.com/meteora8888/AdoKod.git meteora8888/AdoKod
Cloning into 'meteora8888/AdoKod'...
$ cd meteora8888/AdoKod
0.30s$ git fetch origin +refs/pull/3/merge:
From https://github.com/meteora8888/AdoKod
 * branch            refs/pull/3/merge -> FETCH_HEAD
$ git checkout -qf FETCH_HEAD
Setting environment variables from repository settings
$ export DANGER_GITHUB_API_TOKEN=[secure]
rvm
1.53s$ rvm use default
Using /Users/travis/.rvm/gems/ruby-2.4.5
ruby.versions
$ ruby --version
ruby 2.4.5p335 (2018-10-18 revision 65137) [x86_64-darwin17]
$ rvm --version
rvm 1.29.4 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]
$ bundle --version
Bundler version 1.17.1
$ gem --version
2.7.7
install.1
17.11s$ npm install -g danger
npm WARN deprecated @babel/polyfill@7.4.4: 🚨 As of Babel 7.4.0, this
npm WARN deprecated package has been deprecated in favor of directly
npm WARN deprecated including core-js/stable (to polyfill ECMAScript
npm WARN deprecated features) and regenerator-runtime/runtime
npm WARN deprecated (needed to use transpiled generator functions):
npm WARN deprecated 
npm WARN deprecated   > import "core-js/stable";
npm WARN deprecated   > import "regenerator-runtime/runtime";
/usr/local/bin/danger -> /usr/local/lib/node_modules/danger/distribution/commands/danger.js
/usr/local/bin/danger-js -> /usr/local/lib/node_modules/danger/distribution/commands/danger.js
/usr/local/bin/danger-pr -> /usr/local/lib/node_modules/danger/distribution/commands/danger-pr.js
/usr/local/bin/danger-runner -> /usr/local/lib/node_modules/danger/distribution/commands/danger-runner.js
/usr/local/bin/danger-process -> /usr/local/lib/node_modules/danger/distribution/commands/danger-process.js
/usr/local/bin/danger-ci -> /usr/local/lib/node_modules/danger/distribution/commands/danger-ci.js
/usr/local/bin/danger-init -> /usr/local/lib/node_modules/danger/distribution/commands/danger-init.js
/usr/local/bin/danger-local -> /usr/local/lib/node_modules/danger/distribution/commands/danger-local.js
/usr/local/bin/danger-reset-status -> /usr/local/lib/node_modules/danger/distribution/commands/danger-reset-status.js
> core-js@2.6.9 postinstall /usr/local/lib/node_modules/danger/node_modules/core-js
> node scripts/postinstall || echo "ignore"
+ danger@8.0.0
added 302 packages from 187 contributors in 16.066s
install.2
37.24s$ swift build
Fetching https://github.com/danger/swift.git
Fetching https://github.com/shibapm/Logger
Fetching https://github.com/JohnSundell/Marathon
Fetching https://github.com/nerdishbynature/octokit.swift
Fetching https://github.com/JohnSundell/Files.git
Fetching https://github.com/JohnSundell/ShellOut.git
Fetching https://github.com/JohnSundell/Require.git
Fetching https://github.com/JohnSundell/Releases.git
Fetching https://github.com/nerdishbynature/RequestKit.git
Completed resolution in 6.06s
Cloning https://github.com/nerdishbynature/RequestKit.git
Resolving https://github.com/nerdishbynature/RequestKit.git at 2.3.0
Cloning https://github.com/nerdishbynature/octokit.swift
Resolving https://github.com/nerdishbynature/octokit.swift at 0.9.0
Cloning https://github.com/danger/swift.git
Resolving https://github.com/danger/swift.git at 1.5.6
Cloning https://github.com/shibapm/Logger
Resolving https://github.com/shibapm/Logger at 0.2.3
Cloning https://github.com/JohnSundell/ShellOut.git
Resolving https://github.com/JohnSundell/ShellOut.git at 2.2.0
Cloning https://github.com/JohnSundell/Marathon
Resolving https://github.com/JohnSundell/Marathon at 3.2.0
Cloning https://github.com/JohnSundell/Require.git
Resolving https://github.com/JohnSundell/Require.git at 2.0.1
Cloning https://github.com/JohnSundell/Releases.git
Resolving https://github.com/JohnSundell/Releases.git at 4.0.0
Cloning https://github.com/JohnSundell/Files.git
Resolving https://github.com/JohnSundell/Files.git at 2.3.0
Compile Swift Module 'Logger' (1 sources)
Compile Swift Module 'RequestKit' (3 sources)
Compile Swift Module 'DangerShellExecutor' (1 sources)
Compile Swift Module 'OctoKit' (14 sources)
Compile Swift Module 'Danger' (15 sources)
Linking ./.build/x86_64-apple-macosx10.10/debug/libDanger.dylib
Compile Swift Module 'AdoKod' (1 sources)
25.52s$ swift run danger-swift ci
Compile Swift Module 'ShellOut' (1 sources)
Compile Swift Module 'RunnerLib' (14 sources)
Compile Swift Module 'Require' (1 sources)
Compile Swift Module 'Files' (1 sources)
Compile Swift Module 'Releases' (4 sources)
Compile Swift Module 'MarathonCore' (29 sources)
Compile Swift Module 'Runner' (6 sources)
Linking ./.build/x86_64-apple-macosx10.10/debug/danger-swift
Failing the build, there is 1 fail.
Feedback: https://github.com/meteora8888/AdoKod/pull/3#issuecomment-500513955
The command "swift run danger-swift ci" exited with 0.
Done. Your build exited with 0.

Every time I try a pull request lint passes but Danger fails on the like let danger = Danger(). When I comment it out it passes.

**Comment by f-meloni** [comment]
Hey!
Had a look at your repo, and found this:
https://github.com/meteora8888/AdoKod/blob/master/Dangerfile.swift#L14

The problem is that you have those lines in your `Dangerfile`
```
// You can use these functions to send feedback:
message("Highlight something in the table")
warn("Something pretty bad, but not important enough to fail the build")
fail("Something that must be changed")
markdown("Make sure not to ignore warnings!")
```
They are probably from the docs, but they are just examples, if you remove those line it should just work fine :)

**Comment by meteora8888** [comment]
Thank you. That's great . Didn't realize that I was actually failing it myself ;D Sorry I sometimes look so deep that I don't see on the surfase. You helped me a lot thanks.
