### ISSUE TITLE
Support GitLab CI

### ISSUE THREAD

**Issue by mollyIV** [danger/swift#247]
#### Motivation Behind Feature

As a `danger-swift` library client I would like to use it for a project hosted on GitLab CI provider.

#### Feature Description

According to [the documentation](https://danger.systems/swift/tutorials/architecture.html):

> Danger Swift is powered by Danger JS. Think of it as a Swift sandwich: `[Danger JS] -> [Danger Swift] -> [Danger JS]`. Danger JS first gets all the CI and Platform metadata, then passes that to Danger Swift, which returns the results of your Swift rules back to Danger JS.

`danger-swift` needs to get CI and Platform metadata from `danger-js`. 

`danger-js` haven't been supporting GitLab for quite a long time, however recently [Adds support for GitLab CI](https://github.com/danger/danger-js/pull/855) PR has been merged 🎊 

It means that from now on `danger-swift` project can add GitLab CI support 👍

**Comment by mollyIV** [comment]
If you guys do not mind, I would be happy to tackle this one 🚀 🙇

**Comment by f-meloni** [comment]
Hi :)
I've opened the PR for the GitLab support 3 days ago https://github.com/danger/swift/pull/246

**Comment by f-meloni** [comment]
Hi :)
I've already opened the PR for the GitLab support #246

**Comment by mollyIV** [comment]
Oh, that's great 👍 I just couldn't find the issue, that's why I created this one 🙂 

Maybe we could link this issue to your PR description? 🙏

**Comment by f-meloni** [comment]
Sure! :)

Il giorno mer 19 giu 2019 alle 09:18 Daniel Jankowski <
notifications@github.com> ha scritto:

**Comment by f-meloni** [comment]
Sure! :)
