### ISSUE TITLE
Danger fails to run with swiftpm error:command failed which danger

### ISSUE THREAD

**Issue by prasadp-qp** [danger/swift#260]
Danger installed using swift package manager fails to run commands - ci, local, pr.

DEBUG="*" swift run danger-swift local
[2/2] Linking ./.build/x86_64-apple-macosx/debug/danger-swift
Launching Danger Swift local (v1.6.5)
Finding out where the danger executable is
ERROR: commandFailed(command: "which danger", exitCode: 1, stdout: "", stderr: "")

Installing danger using brew resolves this issue. Does this mean, danger must be installed using swift package as well as home-brew?

**Comment by f-meloni** [comment]
Danger swift needs Danger-js.
There are 3 ways to provide Danger-js to Danger-swift:
- Install danger-js via npm
- Install danger-js via brew
- Take the danger-js executable, put it somewhere in your repo and link it pass it to danger-swift with --danger-js-path ... (e.g. `swift run danger-swift local --danger-js-path bin/danger`)

**Comment by prasadp-qp** [comment]
Looks like I need to install danger swift via brew or npm, so that dependent module Danger-js also gets installed.

The Getting Started page suggested to use SwiftPM to lock the version on to my project. That's where I ended up using SwiftPM and not home-brew. 

Thanks @f-meloni.

**Comment by f-meloni** [comment]
Yes that is a valid alternative, SPM solution is my favourite because is more performant, but there is no automatic danger-js installing
