### ISSUE TITLE
Release 2.0.3 won't build

### ISSUE THREAD

**Issue by rogerluan** [danger/swift#273]
Hello.

`swift build` fails to build since the release from yesterday, 2.0.3, with the following error:

```
added 296 packages from 184 contributors in 17.016s
887Fetching https://github.com/JohnSundell/Files.git
888Fetching https://github.com/JohnSundell/ShellOut.git
889Fetching https://github.com/nerdishbynature/octokit.swift
890Fetching https://github.com/JohnSundell/Require.git
891Fetching https://github.com/JohnSundell/Marathon
892Fetching https://github.com/shibapm/Logger
893Fetching https://github.com/JohnSundell/Releases.git
894Fetching https://github.com/danger/swift.git
895Fetching https://github.com/nerdishbynature/RequestKit.git
896error: the package swift[https://github.com/danger/swift.git] @ 2.0.3 contains incompatible dependencies:
897    marathon[https://github.com/JohnSundell/Marathon] @ 79f0561a6d31b22f1f6d87ef4c8ddae6cf39aec5
898The command "./env/scripts/travis-install.sh" failed and exited with 1 during .
```

As a temporary measure, I changed my Package.swift from:
```
.package(url: "https://github.com/danger/swift.git", from: "2.0.2"),
```
to
```
.package(url: "https://github.com/danger/swift.git", .exact("2.0.2")),
```

Happy to provide any more relevant info.

Thanks!

**Comment by f-meloni** [comment]
Hi :),
Which version of swift are you using?

**Comment by rogerluan** [comment]
```Apple Swift version 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5)
Target: x86_64-apple-darwin18.7.0```

(so is my Travis apparently)

Is that the problem? 🤔

**Comment by rogerluan** [comment]
It also fails locally, not only on CI, though.
I've always had cache, it had smoothly everyday until yesterday 😅 

So, I cleaned cache and changed back to `from: "2.0.2"` and noticed that 1) it installed 2.0.2 and 2) it succeeded.
But once I change to `from: "2.0.3"` it fails with the error above.

AFAIK the `from` will try to use the latest version, starting from that version, right? So I don't know why the first run installed 2.0.2 and not 2.0.3, but before, in tests prior to creating this issue, I had `from: "2.0.2"` and it still tried to install 2.0.3.

Thoughts? 🤔

**Comment by f-meloni** [comment]
Can you please delete `.build` and try again with 2.0.3? Is the problem still there?

**Comment by f-meloni** [comment]
I just released 2.0.4 that is using a version of Marathon instead of a review, can you have a look at that to see if fixes your problem?

**Comment by rogerluan** [comment]
v2.0.4 works @f-meloni 👌

**Comment by rogerluan** [comment]
(deleting build ad trying again with 2.0.3 doesn't work)

**Comment by f-meloni** [comment]
Yeah, the problem was the same of https://github.com/Moya/Moya/pull/1921 :)

**Comment by rogerluan** [comment]
Awesome, thanks @f-meloni !
