### ISSUE TITLE
ERROR: Failed to parse JSON (missing allow_collaboration)

### ISSUE THREAD

**Issue by fortmarek** [danger/swift#279]
Hi 👋 

we are trying to run `danger-swift` on jenkins for Gitlab's MR, but we keep getting "Could not get the results JSON file at /tmp/danger-response.json"

This is the complete command with output:
```
danger-swift pr https://our-gitlab-server/iOS/project-name/merge_requests/134
Starting Danger PR on iOS/project-name#134
ERROR: Failed to parse JSON: keyNotFound(CodingKeys(stringValue: "allow_collaboration", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "danger", intValue: nil), CodingKeys(stringValue: "gitlab", intValue: nil), CodingKeys(stringValue: "mr", intValue: nil)], debugDescription: "No value associated with key CodingKeys(stringValue: \"allow_collaboration\", intValue: nil) (\"allow_collaboration\").", underlyingError: nil))

ERROR: Dangerfile eval failed at Dangerfile.swift
ERROR: Could not get the results JSON file at /tmp/danger-response.json

Danger: ⅹ Failing the build, there is 1 fail.
## Failures
danger-swift` failed.
## Markdowns
### Log
```

We have added Gitlab to Jenkins provider already: https://github.com/danger/danger-js/pull/922

It seems like `allow_collaboration` key is missing (I checked the JSON, it isn't there) - but I do not see a way how to add it; maybe it's more of an issue of `danger-js`? (if so, I can create an issue there)

**Comment by f-meloni** [comment]
Some properties that were defined as mandatory in the DSL, sometimes come nil on the response (and that means they were not really mandatory), there are many reasons for that to happen, the main reason is that the gitlab/bitbucket implementations are pretty new here on danger, and the doc was not completely correct, we are updating them when needed.
The solution to this problem is usually make the value optional https://github.com/danger/swift/blob/master/Sources/Danger/GitLabDSL.swift#L166.
But in this specific case it sounds strange to me that `allow_collaboration` is not present, given it `Allow commits from members who can merge to the target branch`, then should always be true or false I suppose.

**Comment by fortmarek** [comment]
We'd like not to maintain our own fork, if possible - besides, I have changed it to optional, but the error is the same which is ... weird? I am running in `swift run danger-swift pr https://our-gitlab-server/iOS/project-name/merge_requests/134` in the folder of the changed `danger-swift`; is there something I'm missing?

**Comment by f-meloni** [comment]
Is the error pointing to the same property? It could be that another one is optional too, but you couldn't see it before, because it was hidden from the first one.
About the fork: feel free to open a PR with your changes here on this repo, I will make a new release with those in, then you will still be pointing to this repo, and would get the changes the community makes, and all the new versions.

**Comment by fortmarek** [comment]
Yes, to the same property, but only if I run it like this `../danger-swift/.build/debug/danger-swift ci pr https://url` (yes, I run before that `swift build`); if I do `swift run danger-swift ci pr https://url` it only outputs this:
ERROR: Dangerfile eval failed at Dangerfile.swift
ERROR: Could not get the results JSON file at /tmp/danger-response.json

**Comment by fortmarek** [comment]
OK, not sure why `../danger-swift/.build/debug/danger-swift ci pr https://url` does not work but when further debugging with `swift run`, `fileManager.fileExists(atPath: dangerResponsePath)` is equal to false in `Runner.swift` (just before line `guard fileManager.contents(atPath: dangerResponsePath) != nil else {`) 

Aka not sure how decoding could influence this?

**Comment by f-meloni** [comment]
I think that is because you are running it without using danger-js, the correct command for testing a PR is `swift run danger-swift pr prlink` is this what you are using?

**Comment by fortmarek** [comment]
I was running `swift run danger-swift ci pr prlink`, but the error is the same with the command you posted.

**Comment by fortmarek** [comment]
So, was able to trigger this error now: 
ERROR: Failed to parse JSON: dataCorrupted(Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "danger", intValue: nil), CodingKeys(stringValue: "gitlab", intValue: nil), CodingKeys(stringValue: "mr", intValue: nil), CodingKeys(stringValue: "state", intValue: nil)], debugDescription: "Cannot initialize State from invalid String value opened", underlyingError: nil))

The problem seems to be using `opened` and not `open` for `State`.

**Comment by fortmarek** [comment]
So, now that I fixed that I am back to only getting this error:
ERROR: Dangerfile eval failed at Dangerfile.swift
ERROR: Could not get the results JSON file at /tmp/danger-response.json 

No more `failed to parse JSON`
🙈 🙈 

Any tips on how I can try to debug it now?

**Comment by f-meloni** [comment]
are you using Swift 5.0 on linux?

**Comment by fortmarek** [comment]
On macOS

**Comment by f-meloni** [comment]
Is because I saw this `/lib/x86_64-linux-gnu/libpthread.so.0``/lib/x86_64-linux-gnu/libc.so.6` 🤔

**Comment by f-meloni** [comment]
Which command are you running?

**Comment by fortmarek** [comment]
Sorry, forgot it was in Docker, it's the Linux issue: https://github.com/danger/swift/issues/214

Closing, it seems to work when downgrading to Swift 4.2, I'll create a PR later today with the made changes for gitlab. 

Thanks for the help.
