### ISSUE TITLE
Failed to parse JSON for dependabot PR's

### ISSUE THREAD

**Issue by ashfurrow** [danger/swift#281]
We're experimenting with GitHub's new dependabot for automated security updates. [This PR failed](https://github.com/artsy/eigen/pull/2918) because danger-swift was unable to parse the resulting JSON:

```
�[31mERROR: Failed to parse JSON: dataCorrupted(Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "danger", intValue: nil), CodingKeys(stringValue: "github", intValue: nil), CodingKeys(stringValue: "issue", intValue: nil), CodingKeys(stringValue: "user", intValue: nil), CodingKeys(stringValue: "type", intValue: nil)], debugDescription: "Cannot initialize UserType from invalid String value Bot", underlyingError: nil))
�[0;0m�[31mERROR: Dangerfile eval failed at Dangerfile.swift
�[0;0m�[31mERROR: Could not get the results JSON file at /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/danger-response.json
�[0;0m
```

The relevant problem appears to be this: `Cannot initialize UserType from invalid String value Bot`. The GitHub API response JSON is apparently different for bots, but I haven't looked into it yet. I actually won't have time for a while to investigate, but wanted to file the bug in case others are hitting this (or have an idea to fix it).

**Comment by ashfurrow** [comment]
Following up, I opened a [fresh pull request](https://github.com/artsy/eigen/pull/2920) using the same commits. My thinking was that if the PR author was a normal GitHub user, then we'd avoid the parsing error. But it appears to be at the commit-level as well:

```
�[31mERROR: Failed to parse JSON: dataCorrupted(Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "danger", intValue: nil), CodingKeys(stringValue: "github", intValue: nil), CodingKeys(stringValue: "commits", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "author", intValue: nil), CodingKeys(stringValue: "type", intValue: nil)], debugDescription: "Cannot initialize UserType from invalid String value Bot", underlyingError: nil))

```

**Comment by f-meloni** [comment]
Hey @ashfurrow,
Can you please tell me which version of Danger-swift are you currently using?
Because I think the problem you currently have was fixed on 1.6.2 https://github.com/danger/swift/pull/251

**Comment by ashfurrow** [comment]
Agh! My apologies for not checking if we were on the latest version. I've updated and am re-running the PR, and will follow up on the results. Thank you :bow:

**Comment by ashfurrow** [comment]
Yup, looks like that did it – thanks again!

**Comment by f-meloni** [comment]
No problem :)
