### ISSUE TITLE
Could not get the contents

### ISSUE THREAD

**Issue by fortmarek** [danger/swift#282]
Hello again!

OK, so following up on https://github.com/danger/swift/issues/279, I have been trying to run `danger-swift` to ensure that the changes I have made for Gitlab are right, but I can't seem to get it to work.

When I run `swift run danger-swift pr path_to_pr`, I am getting this error: 
```sh
Could not get the contents of 'Sources/DangerDependencies/Fake.swift', failing the Dangerfile evaluation.
danger-results://tmp/danger-response.json

ERROR: Dangerfile eval failed at Dangerfile.swift
```

I have created `Fake.swift` according to docs (otherwise the command passes, but generates no output).

This is what my `Package.swift` looks like:
```swift
// swift-tools-version:4.2
import PackageDescription

let package = Package(
    name: "FlashSport",
    products: [
        .library(name: "DangerDeps", type: .dynamic, targets: ["DangerDependencies"]),
    ],
    dependencies: [
      .package(url: "https://github.com/danger/swift.git", from: "2.0.2"),
    ],
    targets: [
        // This is just an arbitrary Swift file in our app, that has
        // no dependencies outside of Foundation, the dependencies section
        // ensures that the library for Danger gets build also.
         .target(name: "DangerDependencies", dependencies: ["Danger"]),
    ]
)
```

My `Dangerfile.swift` is more or less empty, only with a warning to trigger some output and `import Danger; let danger = Danger()`

I feel bad for creating a new issue, but I am just stuck 😞

**Comment by f-meloni** [comment]
This is an issue that is not simple to debug, but I notice that you are not shipping your package with SPM, then you probably can use a real file, and not a fake one, like `eigen` does for example https://github.com/artsy/eigen/blob/master/Package.swift#L18

**Comment by fortmarek** [comment]
Yep, that fixed it, thanks 🎊
