### ISSUE TITLE
Exit status

### ISSUE THREAD

**Issue by fortmarek** [danger/swift#284]
Hi,

when I run `danger-swift local` that runs `fail()` inside its `Dangerfile.swift`, the return code seems to be 0 - should not that be 1?

Also, I tried to simulate `danger-js` process completely and ran as docs suggested:
```bash
swift build && cat Fixtures/eidolon_609.json | ./.build/debug/danger-swift
```
but that returns "ERROR: Invalid DSL JSON data", so I think it'd be good idea to fix that, too (or am I forgetting something?)

**Comment by f-meloni** [comment]
I think you can use `--failsOnError` option

**Comment by f-meloni** [comment]
Closing it, feel free to reopen it if `--failOnError` is not working

**Comment by fortmarek** [comment]
Sorry, completely forgot to write back, it worked, indeed, thanks!

**Comment by Fab1n** [comment]
Does this still work?
