### ISSUE TITLE
Cannot find danger at path location

### ISSUE THREAD

**Issue by jrabek** [danger/swift#290]
# Summary
 
Using the SPM approach to installing danger ran into the following error:
```
$ swift run danger-swift pr https://github.com/danger/swift/pull/95
/bin/bash: /usr/local/bin/danger: No such file or directory
ERROR: The installed danger-js version is below the minimum supported version
Current version =
Minimum supported version = 6.1.6
```

Even though there is a binary at that path
```
$ /usr/local/bin/danger -V
9.1.5
```

Note that this also happens if I use `npm` instead of `brew` to install danger.  In that case I get a similar error that the binary cannot be found even though it is present.

# More Details

Package.swift
```
// swift-tools-version:4.2
import PackageDescription

let package = Package(
    name: "Eigen",
    dependencies: [
      .package(url: "https://github.com/danger/swift.git", from: "1.0.0")
    ],
    targets: [
        // This is just an arbitrary Swift file in our app, that has
        // no dependencies outside of Foundation, the dependencies section
        // ensures that the library for Danger gets build also.
        .target(name: "dummy", dependencies: ["Danger"], path: "danger", sources: ["dummy.swift"]),
    ]
)
```

**Comment by f-meloni** [comment]
Are you using the -g path to install it right?
if you install it with npm and then you run `which danger` what do you get?

**Comment by jrabek** [comment]
So I tried with both `npm install -g danger@^6.0.0` and then `brew install danger/tap/danger-swift`.  In both cases `which danger` gave the expected path of `~/.nvm/versions/node/v8.9.0/bin/danger` for npm and `/usr/local/bin/danger` for when using brew.

At first I thought `nvm` would be the issue but the brew installation resulted in the same issue.

The path being printed out when running `$ swift run danger-swift pr https://github.com/danger/swift/pull/95` was always the path where danger was actually located but swift was reporting it couldn't find it.

I ended up using `danger-swift` to work around it.

**Comment by f-meloni** [comment]
This is really strange, danger uses `command -v` to find where the executable is, and we use it here on CI as well (you can look at https://github.com/danger/swift/blob/master/.travis.yml#L64 to see if that helps).
Another alternative could be having danger on your repo https://github.com/danger/swift#local-compiled-danger-js

**Comment by jrabek** [comment]
btw, I realized that in the getting started guide it still references `1.0.0` and I just copied it verbatim without thinking.

I updated my Package.swift to pull the latest version:
```
.package(url: "https://github.com/danger/swift.git", from: "2.0.6")
```

And I don't get this error any more.

**Comment by f-meloni** [comment]
I've updated the README to have the 2.0.0 👍🏻
