### ISSUE TITLE
Use Docker Hub to speed up GitHub Action

### ISSUE THREAD

**Issue by bofeizhu** [danger/swift#292]
Danger/Swift's GitHub Action currently takes 5min to build. If we upload it to Docker Hub, it could run much faster. https://github.com/actions/cache/issues/81#issuecomment-552680709

**Comment by f-meloni** [comment]
This is a really good idea!
I think we could use github package registry

> Now, we can pull a docker image from the Docker Hub or the GitHub Package Registry to skip a build step.

With rocket we can generate a package when we release :)

**Comment by orta** [comment]
I don't trust dockerhub anymore - I've been moving danger-js to GitHub's docker images, think I'm close 

https://github.com/danger/danger-js/pull/938

**Comment by f-meloni** [comment]
Interesting, would be cool understand if we can actually point GitHub's docker images in actions

**Comment by bofeizhu** [comment]
@f-meloni Also, could we add `SwiftLint` installation to the danger?

**Comment by f-meloni** [comment]
If we manage to not have to build the image all the times yes.
Adding swiftlint brings the building times to 10 minutes.
An alternative would be have another Dockerfile that contains swiftlint and uses rocket to make a tagged commit (e.g. `2.07-swiftlint`).
I would be happy to take a PR for that

**Comment by f-meloni** [comment]
Closing because now we have a package here on GitHub, both with and without Swiftlint

https://github.com/orgs/danger/packages/container/package/danger-swift
https://github.com/orgs/danger/packages/container/package/danger-swift-with-swiftlint
