### ISSUE TITLE
Danger Swift should error with a nice message if danger js isn't available

### ISSUE THREAD

**Issue by peacemoon** [danger/swift#294]
I'm trying to convert my travis configuration to Github Action, most of the steps are converted, only danger swift has some problem that it doesn't work.

This is the configuration I have https://github.com/superarcswift/SwiftCommunity/blob/bugfix/github_action/.github/workflows/main.yml#L37

And this is the error from Github Action
![Screenshot 2019-11-23 at 08 59 13](https://user-images.githubusercontent.com/478757/69475618-8ccf2b00-0dcf-11ea-9d1e-7b1d1b84b074.png)

https://github.com/superarcswift/SwiftCommunity/pull/120/checks?check_run_id=316993774

As mentioned, the same line of code works perfectly on travis.

Anyone has more insights how to run it on Github Action?

**Comment by orta** [comment]
maybe danger isn't installed in npm?

**Comment by peacemoon** [comment]
yep, true, it looks better after and add installation script https://github.com/superarcswift/SwiftCommunity/blob/bugfix/github_action/.github/workflows/main.yml#L37

Thank you for pointing it out.

**Comment by orta** [comment]
No worries (BTW you can probably delete `bundle install` from those steps)

I'm gonna re-open this as Danger Swift should show an error message if danger can't be found
