### ISSUE TITLE
danger-swift always return a status of 0.

### ISSUE THREAD

**Issue by scottandrew** [danger/swift#306]
```
if let body = danger.github.pullRequest.body {
    if (body.contains("https://xxx.atlassian.net/browse/???")) {
        danger.fail("Forgot to link to Jira ticket!")
    }

    if (!body.contains("[x]")) {
        danger.fail("Forgot to mark a type in the checklist!")
    }
} else {
    danger.fail("Missing pull request message")
}
```
I see the failure in our pull request and it fails the pull request. However it returns a 0 error code. Should it be returning 1? Can I force it to return 1? I saw a note on --failOnError but this isn't supported if I try it locally.

**Comment by orta** [comment]
I'm pretty sure that flag exists, check danger Js's docs

**Comment by scottandrew** [comment]
Its working never mind.
