### ISSUE TITLE
Error running swift build after Xcode 11.4 update

### ISSUE THREAD

**Issue by bofeizhu** [danger/swift#327]
Error message:
`'OctoKit' ***/.build/checkouts/octokit.swift: error: target at '/
***/.build/checkouts/octokit.swift' contains mixed language source files; feature not supported`

**Comment by orta** [comment]
I'd recommend looking into that issue with octokit.swift and then coming back and updating Danger to the new version 👍

**Comment by bofeizhu** [comment]
@orta I submit a PR for OctoKit https://github.com/nerdishbynature/octokit.swift/pull/102

**Comment by bofeizhu** [comment]
@f-meloni could you update the octokit version? The patch is merged. Thank you!

**Comment by f-meloni** [comment]
That is already been updated on https://github.com/danger/swift/pull/329 :)

**Comment by bofeizhu** [comment]
Great!
