### ISSUE TITLE
Support GitHub draft state

### ISSUE THREAD

**Issue by captainbarbosa** [danger/swift#328]
GitHub now supports marking [pull requests as drafts](https://github.blog/2019-02-14-introducing-draft-pull-requests/). It would be super useful to be able to check for this in a Dangerfile.

Perhaps this could be a new addition to `PullRequestState`?

https://github.com/danger/swift/blob/869b5c82c820b4079a8aa43506b72ebe131ba0eb/Sources/Danger/GitHubDSL.swift#L58-L63

**Comment by orta** [comment]
Double check the API responses on the GitHub developer site, this basically has to match that - but I bet it's probably what you recommend, then send along a PR 👍

**Comment by captainbarbosa** [comment]
Looks like draft state is available as a preview [as of Feb 2019](https://developer.github.com/changes/2019-02-14-draft-pull-requests/). Its noted as a boolean on a [PR's response object](https://developer.github.com/v3/pulls/#get-a-single-pull-request):

```
 { ...
  "draft": false,
  "merged": false,
  "mergeable": true,
  "rebaseable": true,
  "mergeable_state": "clean",
  "merged_by": { ... },
  "comments": 10,
  "review_comments": 0,
  "maintainer_can_modify": true,
  "commits": 3,
  "additions": 100,
  "deletions": 3,
  "changed_files": 5
}
```

I believe this might require a change back in [Octokit.swift](https://github.com/nerdishbynature/octokit.swift/blob/master/OctoKit/PullRequest.swift) though. I'll look into that.

**Comment by f-meloni** [comment]
I think you should be able to just add it to the Danger DSL, I suggest to use a separated property thought, as it is in the GitHub API, to avoid too much mess in the decoding, where you will have otherwise to merge the two decoded properties manually
