### ISSUE TITLE
Danger Swift installed through Homebrew - danger-swift pr; [!] Unknown option: `--process` Did you mean: --pry?

### ISSUE THREAD

**Issue by dejanskledar** [danger/swift#349]
I wanted to test danger-swift installed from Homebrew, through this guide:

https://danger.systems/swift/guides/getting_started.html

But, after running

```sh
danger-swift pr https://github.com/danger/swift/pull/318
```

I get this error:

```sh
➜  ~ danger-swift pr https://github.com/danger/swift/pull/318
[!] Unknown option: `--process`
Did you mean: --pry?

Usage:

    $ danger pr

      Run the Dangerfile locally against Pull Requests (works with forks, too). Does
      not post to the PR. Usage: danger pr <URL>

Options:

    --clear-http-cache                  Clear the local http cache before running
                                        Danger locally.
    --pry                               Drop into a Pry shell after evaluating the
                                        Dangerfile.
    --dangerfile=<path/to/dangerfile>   The location of your Dangerfile
    --verify-ssl                        Verify SSL in Octokit
```

If I try to run it with `local` and passing the Dangerfile to it:

```sh
➜  ~ danger-swift local —dangerfile Dangerfile.swift
[!] Unknown option: `--process`
Did you mean: --pry?

Usage:

    $ danger local

      Run the Dangerfile locally. This command is generally deprecated in favor of
      `danger pr`.

Options:

    --use-merged-pr=[#id]   The ID of an already merged PR inside your history to use
                            as a reference for the local run.
    --clear-http-cache      Clear the local http cache before running Danger locally.
    --pry                   Drop into a Pry shell after evaluating the Dangerfile.
➜  ~
```

What am I missing?

**Comment by f-meloni** [comment]
Do you have Danger ruby installed on your machine? If yes I think that is the issue

**Comment by dejanskledar** [comment]
> Do you have Danger ruby installed on your machine? If yes I think that is the issue

You were right! Indeed I had a ruby version installed too:

```sh
➜  ~ which danger
/Users/*****/.rvm/gems/ruby-2.6.3/bin/danger
```

Fixed with:
```sh
gem uninstall danger
```

Uninstalling Ruby danger did the trick, if anyone else has the same issue.

Thank you. 😃

**Comment by orta** [comment]
Could make it use `danger-js` which should always be installed when danger-js is installed and not clash

**Comment by f-meloni** [comment]
Is it there also if you install danger with Brew?

**Comment by orta** [comment]
Confirmed, that's a no - it is a zip file with just a 'danger' executable. Shame. Doesn't mean it can't try use `danger-js` first before falling back to `danger`, but I bet that's already in there.

**Comment by f-meloni** [comment]
No, it is not, this is a great idea, will have a look at adding it :)
