### ISSUE TITLE
Setup DangerSwift on Bitrise CI can't get correct information from PRs

### ISSUE THREAD

**Issue by karinyfreitas** [danger/swift#360]
I'm using Bitrise CI and Bitbucket Cloud with a Swift Project. Then I'm trying to add a step on my workflow to check when there are some Pull Requests and make comments. 

So my workflow step looks like:
```
script@1:
     inputs:
     - content: |-
          #!/usr/bin/env bash
          # fail if any commands fails
          set -ex
          echo "Danger instalation"
          brew install danger/tap/danger-swift
          danger-swift ci
    title: Run Danger
```

And this is my Dangerfile.swift:
```
import Danger
let danger = Danger()
danger.message("Hello from Danger")
```

I'm also setting on Environment Variables both **"DANGER_BITBUCKETCLOUD_OAUTH_KEY"** and **"DANGER_BITBUCKETCLOUD_OAUTH_SECRET"** from Bitbucket's OAuth consumers.
But on my PR I receive this message:

```
[31mERROR: Failed to parse JSON: keyNotFound(CodingKeys(stringValue: "account_id", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "danger", intValue: nil), CodingKeys(stringValue: "bitbucket_cloud", intValue: nil), CodingKeys(stringValue: "activities", intValue: nil), _JSONKey(stringValue: "Index 1", intValue: 1), CodingKeys(stringValue: "comment", intValue: nil), CodingKeys(stringValue: "user", intValue: nil)], debugDescription: "No value associated with key CodingKeys(stringValue: \"account_id\", intValue: nil) (\"account_id\").", underlyingError: nil))
[0;0m[31mERROR: Dangerfile eval failed at Dangerfile.swift
[0;0m[31mERROR: Could not get the results JSON file at /var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/danger-response.json
[0;0m
Generated by 🚫 dangerJS against ffa2cec8552d
```

Do you have any idea of what I could be missing? Thanks in advance.

**Comment by f-meloni** [comment]
From what I see from the error message is missing one expected value, that is at

```
danger. bitbucket_cloud. activities[1].comment.user.account_id
```

This looks odd, because I would expect a user that left a comment to have an account id

Could you please share the JSON for that PR (if it contains some data that can not be shared can you just share the part where danger is crashing please? Even a redacted version would be fine)

To get the JSON you can launch `danger-swift pr $prURL --json > file.json`

**Comment by karinyfreitas** [comment]
Thanks for your reply! I tried to run the command you asked. But locally I got:
```
[!] Unknown option: `--process`
Did you mean: --pry?

Usage:

    $ danger pr

      Run the Dangerfile locally against Pull Requests (works with forks, too). Does
      not post to the PR. Usage: danger pr <URL>

Options:

    --clear-http-cache                  Clear the local http cache before running
                                        Danger locally.
    --pry                               Drop into a Pry shell after evaluating the
                                        Dangerfile.
    --dangerfile=<path/to/dangerfile>   The location of your Dangerfile
    --verify-ssl                        Verify SSL in Octokit
```

And on Bitrise, it didn't export any JSON files or showed something on console.
Script:
<img width="859" alt="Captura de Tela 2020-07-27 às 11 32 31" src="https://user-images.githubusercontent.com/18575765/88554555-083b4900-cffd-11ea-9adf-2e5906b027a7.png">

Output:
<img width="1175" alt="Captura de Tela 2020-07-27 às 11 29 37" src="https://user-images.githubusercontent.com/18575765/88554336-c6aa9e00-cffc-11ea-9b71-debebf9b9348.png">

**Comment by f-meloni** [comment]
> Thanks for your reply! I tried to run the command you asked. But locally I got:

[!] Unknown option: `--process`
Did you mean: --pry?

Usage:

    $ danger pr

      Run the Dangerfile locally against Pull Requests (works with forks, too). Does
      not post to the PR. Usage: danger pr <URL>

Options:

    --clear-http-cache                  Clear the local http cache before running
                                        Danger locally.
    --pry                               Drop into a Pry shell after evaluating the
                                        Dangerfile.
    --dangerfile=<path/to/dangerfile>   The location of your Dangerfile
    --verify-ssl                        Verify SSL in Octokit


I think you have danger ruby installed, and that is conflicting with the js version that danger-swift uses under the hood.

**Comment by karinyfreitas** [comment]
Yes! **Locally** I had danger ruby installed, then I uninstalled it and the JSON file looks like:
```
Starting Danger PR on wzpsolutionslda/speechbot#110
/usr/local/lib/node_modules/danger/distribution/platforms/bitbucket_cloud/BitBucketCloudAPI.js:86
    throw new Error("Either DANGER_BITBUCKETCLOUD_OAUTH_KEY or DANGER_BITBUCKETCLOUD_USERNAME is not set");
    ^

Error: Either DANGER_BITBUCKETCLOUD_OAUTH_KEY or DANGER_BITBUCKETCLOUD_USERNAME is not set
    at Object.bitbucketCloudCredentialsFromEnv (/usr/local/lib/node_modules/danger/distribution/platforms/bitbucket_cloud/BitBucketCloudAPI.js:86:11)
    at Object.getPlatformForEnv (/usr/local/lib/node_modules/danger/distribution/platforms/platform.js:45:32)
    at Object.<anonymous> (/usr/local/lib/node_modules/danger/distribution/commands/danger-pr.js:130:43)
    at Module._compile (internal/modules/cjs/loader.js:1236:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1257:10)
    at Module.load (internal/modules/cjs/loader.js:1085:32)
    at Function.Module._load (internal/modules/cjs/loader.js:950:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

But I set both **DANGER_BITBUCKETCLOUD_OAUTH_KEY** and **DANGER_BITBUCKETCLOUD_USERNAME** on Bitrise CI:
<img width="1208" alt="Captura de Tela 2020-07-28 às 08 42 46" src="https://user-images.githubusercontent.com/18575765/88661689-4db84e80-d0af-11ea-8d6d-ffb9f81c7ff6.png">

 My problem is that `danger-swift ci` command on a script from Bitrise, the script only has this content:
```
script@1:
     inputs:
     - content: |-
          #!/usr/bin/env bash
          # fail if any commands fails
          set -ex
          echo "Danger instalation"
          brew install danger/tap/danger-swift
          danger-swift ci
    title: Run Danger
```

**Comment by abel3cl** [comment]
Hi @f-meloni 
I have the same problem. This only happens on a subsequent push after the PR is created. I believe it's due to the fact that our bot account doesn't have an account_id. All other users do have.
Attached file.json.zip
[file.json.zip](https://github.com/danger/swift/files/5408270/file.json.zip)


I can make a PR and make the field optional

**Comment by abel3cl** [comment]
I figured out how to do the PR @f-meloni 
If you'd like to review it https://github.com/danger/swift/pull/388
