### ISSUE TITLE
Swift Lint + Danger

### ISSUE THREAD

**Issue by taimur** [danger/swift#366]
/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/tmp_dangerfile.swift:7:11: warning: 'lint(inline:directory:configFile:strict:quiet:lintAllFiles:swiftlintPath:)' is deprecated: Use the lint( lintStyle ..) method instead.
SwiftLint.lint(directory: "sources", configFile: ".swiftlint.yml")
^
/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/tmp_dangerfile.swift:13:11: warning: 'lint(inline:directory:configFile:strict:quiet:lintAllFiles:swiftlintPath:)' is deprecated: Use the lint( lintStyle ..) method instead.
SwiftLint.lint(lintAllFiles: true)
^
/bin/sh: swiftlint: command not found
/bin/sh: swiftlint: command not found
/bin/sh: swiftlint: command not found
/bin/sh: swiftlint: command not found

**Comment by f-meloni** [comment]
Hey,
For the warning, just use the new function. (https://github.com/danger/swift/blob/master/Sources/Danger/Plugins/SwiftLint/SwiftLint.swift#L58)
For the error, you will need to install swiftlint, pass tje swiftlint path, or set swifltint as dependency of your Package.swift

**Comment by taimur** [comment]
Thanks a lot @f-meloni 

Can you please guide me on these.

```
+ echo 'Run danger'
Run danger
+ danger-swift ci
(node:13721) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
/bin/sh: swiftlint: command not found
/bin/sh: swiftlint: command not found
```

This is how my Dangerfile.swift looks like,

```
import Danger

let danger = Danger()
let editedFiles = danger.git.modifiedFiles + danger.git.createdFiles
message("These files have changed:\n \(editedFiles.joined(separator: ", "))")


if danger.git.createdFiles.count + danger.git.modifiedFiles.count - danger.git.deletedFiles.count > 100 {
    warn("Big PR, try to keep changes smaller if you can")
}

// Swift lint
SwiftLint.lint(.modifiedAndCreatedFiles(directory: "virginmobile"), inline: true)
SwiftLint.lint(swiftlintPath: "virginmobile/Pods/SwiftLint/swiftlint")
SwiftLint.lint()

```

**Comment by f-meloni** [comment]
For this

> /bin/sh: swiftlint: command not found
/bin/sh: swiftlint: command not found

you will need to install Swiftlint in your, pass the Swiftlint path to the Dangerfile call if you have the bin in the repo (e.g., installed with Cocoapods), or set Swiftlint as dependency of your Package.swift

**Comment by taimur** [comment]
Thanks a lot for the support - the last warning is about Buffer. 

(node:13786) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
/bin/sh: swiftlint: command not found

**Comment by f-meloni** [comment]
I think that comes from Danger-JS, you could open an issue there if there is not one opened already

**Comment by taimur** [comment]
Hi @f-meloni 
We have recently integrated Danger into our project with CI as Bitrise and Code Repo: Bitbucket.

We are getting this message on each PR. Can you please assist us. Thanks a lot !

`❌ - Error deserializing SwiftLint JSON response (): dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "No value." UserInfo={NSDebugDescription=No value.})))`

**Comment by orta** [comment]
What did you look into based on that error message?

**Comment by taimur** [comment]
Go through the code, Googled tried to find answers related to this issue. Cudnt find anything helpful to fix it and I posted here

**Comment by orta** [comment]
hrm, looks to me like no JSON was passed from SwiftLint back to danger - maybe they have some options around that?

**Comment by taimur** [comment]
This is how my Danger file looks like

```
import Danger

let danger = Danger()
let editedFiles = danger.git.modifiedFiles + danger.git.createdFiles
message("These files have changed:\n \(editedFiles.joined(separator: ", "))")


if danger.git.createdFiles.count + danger.git.modifiedFiles.count - danger.git.deletedFiles.count > 100 {
    warn("Big PR, try to keep changes smaller if you can")
}

// Swift lint
SwiftLint.lint(.modifiedAndCreatedFiles(directory: "virginmobile"), inline: true)
SwiftLint.lint(swiftlintPath: "virginmobile/Pods/SwiftLint/swiftlint")
```

**Comment by taimur** [comment]
and my SwiftLint.yml

```
excluded:
   - Pods

# structure limits
identifier_name: # don't use short variable names, don't use abbreviations
  excluded:
    - id
  min_length:
    error: 2
    warning: 3

disabled_rules:
  - force_try
  - function_body_length
  - line_length
  - nesting
  - todo
  - type_body_length
  - type_name
  - identifier_name
  - cyclomatic_complexity
  - function_parameter_count
  - shorthand_operator
  - file_length
  - trailing_whitespace
  - trailing_comma
  - trailing_newline
  - empty_enum_arguments
  - vertical_whitespace
  - private_over_fileprivate
  - orphaned_doc_comment
  - multiple_closures_with_trailing_closure
  - colon
  - opening_brace
  - no_space_in_method_call
  - control_statement
  - unused_closure_parameter
  - redundant_string_enum_value
  - vertical_parameter_alignment
  - syntactic_sugar
  - implicit_getter
  - empty_parentheses_with_trailing_closure
  - return_arrow_whitespace
  - switch_case_alignment
  - statement_position
  - unneeded_break_in_switch
  - redundant_void_return
  - comma
  - void_return
  - large_tuple
  - weak_delegate
  - redundant_optional_initialization
  - trailing_semicolon
  - for_where
  - computed_accessors_order
  - unused_setter_value
  - redundant_set_access_control
  - closure_parameter_position
  - unused_enumerated
  - mark
  - legacy_constructor
  - unneeded_notification_center_removal
  - class_delegate_protocol
  - block_based_kvo
  - closing_brace
  - unused_optional_binding
  - operator_whitespace
  - leading_whitespace
  - redundant_discardable_let
  - reduce_boolean

# optional linting rules
# some rules are only opt-in
opt_in_rules:
- force_unwrapping
- implicitly_unwrapped_optional

force_cast: warning

# Optional indentation rules, enable for strict indentation/line wrapping
#  - closure_end_indentation
#  - literal_expression_end_indentation
#  - multiline_arguments
#  - multiline_parameters
#  - vertical_parameter_alignment_on_call

# other custom rules

custom_rules:
  array_subscript_access_with_number_literal:
    included: ".*\\.swift"
    name: "array subscript access with number literal"
    regex: '\w+\[\d+\]'
    message: "Make sure not to access the array with a hardcoded literal in the subscript"
    severity: warning

```

**Comment by f-meloni** [comment]
@taimur can you please try to add `allow_zero_lintable_files: true` to your swiftlint.yml?

**Comment by taimur** [comment]
Yeah I tried it but it didn't work.

**Comment by omurolgunay** [comment]
Hi,
In my case danger-swift local was working properly. But i got same error on Bitrise. We don't keep our pods file on git.
So Pods/SwiftLint/swiftlint is not valid path on Bitrise.
I just add "Bitrise.io Cache:Pull" before danger step. (or you just add cocoapods install step). And started working properly.
Now my workflow looks like this https://prnt.sc/uiqlfi

**Comment by taimur** [comment]
@omurolgunay have you guys faced the same error.  
❌ - Error deserializing SwiftLint JSON response ()

**Comment by omurolgunay** [comment]
yes we were getting this error but we solved it by adding the pod installation step

`❌ - Error deserializing SwiftLint JSON response (): dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "No value." UserInfo={NSDebugDescription=No value.})))`

Our Lint step in Dangerfile
`SwiftLint.lint(.modifiedAndCreatedFiles(directory: "YOURPATH"), inline: true, configFile: nil, strict: true, quiet: false, swiftlintPath: "Pods/SwiftLint/swiftlint")`

**Comment by taimur** [comment]
@omurolgunay 
Tried it and it didn't work :(
We don't get any error on Bitrise but on PR's we get this error. 

This is the line I added
`SwiftLint.lint(.modifiedAndCreatedFiles(directory: "virginmobile"), inline: true, configFile: nil, strict: true, quiet: false, swiftlintPath: "virginmobile/Pods/SwiftLint/swiftlint")
`
`❌ - Error deserializing SwiftLint JSON response (): dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "No value." UserInfo={NSDebugDescription=No value.})))`

If convenient can you please assist
@f-meloni @orta

**Comment by taimur** [comment]
It worked thanks a lot !

**Comment by taimur** [comment]
@omurolgunay Unfortunately it didnt work.

This error was removed. But Linting stopped working and all the warnings and errors on the PR were not reported. We got message 
#

> All green. well done 🎉

 from bitrise. But it was misleading as lint has stopped working.

`❌ - Error deserializing SwiftLint JSON response (): dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "No value." UserInfo={NSDebugDescription=No value.})))`

**Comment by 417-72KI** [comment]
@taimur 
Can you try this?

```swift
SwiftLint.lint(.modifiedAndCreatedFiles(directory: "project"), inline: true)
```
↓
```swift
if !(danger.git.createdFiles + danger.git.modifiedFiles).filter({ !$0.contains("Pods") }).isEmpty {
    SwiftLint.lint(.modifiedAndCreatedFiles(directory: "project"), inline: true)
}
```

I think modified or added swift files in your pull request are only in `Pods`, which is excluded by .swiftlint.yml🤔

**Comment by taimur** [comment]
@417-72KI Tried it Didn't work :(

**Comment by taimur** [comment]
> For this
> 
> > /bin/sh: swiftlint: command not found
> > /bin/sh: swiftlint: command not found
> 
> you will need to install Swiftlint in your, pass the Swiftlint path to the Dangerfile call if you have the bin in the repo (e.g., installed with Cocoapods), or set Swiftlint as dependency of your Package.swift.
> 
> EDIT: I noticed you pass the path, but only to the second call, you should pass it to all of them
> 
> ```
> SwiftLint.lint(.modifiedAndCreatedFiles(directory: "virginmobile"), inline: true, swiftlintPath: "virginmobile/Pods/SwiftLint/swiftlint")
> SwiftLint.lint(swiftlintPath: "virginmobile/Pods/SwiftLint/swiftlint")
> SwiftLint.lint(swiftlintPath: "virginmobile/Pods/SwiftLint/swiftlint") // This call is equal to the previous one, why do you need both?
> ```

Fixed using this.

**Comment by thaisconde** [comment]
I had the same problem and i resolved using 
SwiftLint.lint(.modifiedAndCreatedFiles(directory: "projectName"), inline: true, swiftlintPath: "./Pods/SwiftLint/swiftlint")
