### ISSUE TITLE
[discussion] Exclude `Test` folder on SwiftLint.

### ISSUE THREAD

**Issue by 417-72KI** [danger/swift#382]
There is a lot of violations in test sources (e.g. https://github.com/danger/swift/pull/381#discussion_r501453860).
I counted violations with [this script](https://gist.github.com/417-72KI/75fbe862ae5645b7fea67e2645eecdda), and here is a result.

```
1 file_length
1 todo
2 force_try
2 xctfail_message
3 function_body_length
3 type_body_length
7 trailing_whitespace
57 identifier_name
73 trailing_comma
142 line_length
```

When `Tests` is excluded on SwiftLint, the result will be as follows.

```
1 force_try
1 todo
1 trailing_whitespace
3 line_length
4 identifier_name
```

From the above results, we can see that most of the violations are in the test code.

I think violations from SwiftLint should be fixed on source codes, but can be ignored on test codes.

**Comment by f-meloni** [comment]
We have introduced Swiftlint and Swiftformat after more than a year that Danger was already released, so we retro actively went to fix the various issues (and we didn't touch all the files yet).
Some of them are in the JSON, and I'm in favour of ignore them, while I would like to keep the Test files still at a quality that is in line with the rest of the code if possible.
I'm totally fine with having a swiftlint.yml file, or maybe two (one on sources and one on tests), with explicitly written which rules we want to keep and which ones we don't.
I think with a swiftlint.yml is possible to define also that some words are accepted even if too short (e.g., id), and that would help to remove the warnings.

**Comment by 417-72KI** [comment]
@f-meloni Thank you for your opinion.
I tried to include Test files and ignore JSON and auto-generated files.
Additionally, I added some details for `line_length` rule, and `identifier_name` rule.
(ref: #383)

The result has been as follows.

```
1 file_length
1 todo
2 force_try
2 xctfail_message
3 function_body_length
3 type_body_length
7 trailing_whitespace
30 superfluous_disable_command
38 trailing_comma
54 line_length
```
