### ISSUE TITLE
Danger Gitlab DSL fails with protected branch

### ISSUE THREAD

**Issue by kerry** [danger/swift#409]
With a protected branch, danger DSL fails on Gitlab because for protected branches, it fails to read the value for force_remove_source_branch

Making this parameter in the DSL as default false can solve this.

```
ERROR: Failed to parse JSON: valueNotFound(Swift.Bool, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "danger", intValue: nil), CodingKeys(stringValue: "gitlab", intValue: nil), CodingKeys(stringValue: "mr", intValue: nil), CodingKeys(stringValue: "force_remove_source_branch", intValue: nil)], debugDescription: "Expected Bool value but found null instead.", underlyingError: nil))
```

**Comment by 417-72KI** [comment]
The error says `Expected Bool value but found null instead.`, which means `force_remove_source_branch` is disabled in protected branches.

I think it should be optional instead of false as default.
