### ISSUE TITLE
Danger Swift Local doesn't work with `main`

### ISSUE THREAD

**Issue by jonesrajee** [danger/swift#420]
Our primary branch is named `main` not `master`

Running `swift run danger-swift local` doesn't work and produces the following output:

```sh
[2/2] Merging module Logger
Could not get diff from git between master and HEAD
/snapshot/danger-js/distribution/platforms/git/localGetDiff.js:20
            throw new Error(data.toString());
            ^

Error: fatal: ambiguous argument 'master...HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

    at Socket.<anonymous> (/snapshot/danger-js/distribution/platforms/git/localGetDiff.js:20:19)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:182:23)
```

**Comment by orta** [comment]
You need to provide the reference branch param - though I'd take a PR to danger-js which checks to see if master exists and if not checks for main first before bailing

**Comment by jonesrajee** [comment]
@orta Looks like `swift run danger-swift -help` doesn't work. Is there a reference doc to get the command list to pass in the reference branch param?

**Comment by f-meloni** [comment]
You need to run the help on danger-js, we don't yet have anything to pass those from danger-js to danger-swift so that they can be shown on the help.
Would be happy to take PRs for that.

**Comment by jonesrajee** [comment]
@f-meloni I deleted my comment because `swift run danger-swift local -help` does execute!

Also, `swift run danger-swift local -base main` works as well 🚀 

(I do get some errors but it looks like Danger is working now vs bailing)



```sh
swift run danger-swift local --base main
ERROR: Failed to parse JSON: keyNotFound(CodingKeys(stringValue: "url", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "danger", intValue: nil), CodingKeys(stringValue: "git", intValue: nil), CodingKeys(stringValue: "commits", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0)], debugDescription: "No value associated with key CodingKeys(stringValue: \"url\", intValue: nil) (\"url\").", underlyingError: nil))



ERROR: Dangerfile eval failed at Dangerfile.swift

Danger: ⅹ Failing the build, there are 2 fails.
## Failures
Failed to get the coverage - Error: The operation couldn’t be completed. (DangerSwiftCoverage.SPMCoverageParser.Errors error 0.)
-
danger-swift` failed.
## Messages
These files have changed: Tests/DangerDependenciesResolverTests/InlineDependenciesFinderTests.swift, Tests/DangerDependenciesResolverTests/PackageGeneratorTests.swift, Tests/DangerTests/BitBucketServerTests.swift, Tests/DangerTests/DangerUtilsTests.swift, Tests/DangerTests/GitDiffTests.swift, Tests/DangerTests/GitHubTests.swift, Tests/DangerTests/GitLabTests.swift, Tests/DangerTests/SwiftLint/DangerSwiftLintTests.swift, Tests/DangerTests/XCTestManifests.swift, Tests/RunnerLibTests/DangerFileGeneratorTests.swift
## Markdowns
### Log



ERROR: Failed to parse JSON: keyNotFound(CodingKeys(stringValue: "url", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "danger", intValue: nil), CodingKeys(stringValue: "git", intValue: nil), CodingKeys(stringValue: "commits", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0)], debugDescription: "No value associated with key CodingKeys(stringValue: \"url\", intValue: nil) (\"url\").", underlyingError: nil))
danger-results://var/folders/pp/_w2jtc4508lbxk4bgp8h8klw0000gn/T/danger-response.json

ERROR: Dangerfile eval failed at Dangerfile.swift

```

**Comment by f-meloni** [comment]
> @f-meloni I deleted my comment because swift run danger-swift local -help does execute!

Right, is probably because you used `-help` and not `--help`, because that would be interceipt by `!CommandLine.arguments.contains("--help")`.
We might think to always make danger js print the help, but some things are be different in danger-swift (and it has also additional parameters), so would be nice maybe to get a JSON with the supported command or descriptions so that we could construct our help. (But anyway is unrelated with the original issue)

For the issue I think the "fake" json that is generated by danger-js doesn't have a url for the commits, but I think that is always present in the real enviroment (probably @orta knows it better than me), so in that case might be worth to add a fake url manually to the JSON generated in `danger local`.

**Comment by orta** [comment]
Yep, no URL for the commits, it's kind stubbed JSON overall because it has no ties to a remote code host like GitHub / Gitlab etc
