### ISSUE TITLE
Option to preserve messages from previous runs?

### ISSUE THREAD

**Issue by clayellis-cricut** [danger/swift#438]
Is there a way to preserve messages from previous runs that aren't recreated in subsequent runs? I thought that maybe `danger.messages` would contain previous messages from previous runs after it's created, but it just starts as an empty array.

My use case is that I run Danger from two sources on different events: Github Actions when the PR is edited, and Bitrise using the Pull Request trigger. Some messages depend on environment variables from one environment that aren't present when started from the other environment. I'd like to keep certain messages around, but since the message can't be recreated, it gets deleted.

I also tried looking into the GitHubDSL object for an array of comments on the pull request, but all that's there is the count of comments. 

Any ideas here?

**Comment by f-meloni** [comment]
I would suggest to separate the two run using the `--id` parameter, that will create two separate comments, one for each run.

**Comment by clayellis-cricut** [comment]
The goal is to keep the single danger comment, as otherwise there would potentially be duplicate messages from each run. I found a solution:

Using the GitHub API via `danger.github.api` you can retrieve the comments on a PR using `.issueComents(...)`. I get all of the comments and look for one whose body contains the string `"DangerID"` and then, using regular expressions, parse out the messages that I want to keep and then re-emit them. 

That said, it would be really nice to see a plugin that can get all of the Danger comments on a PR and parse them out into `DangerResults` types.
