### ISSUE TITLE
Latest release unhides DangerDeps product causing failures

### ISSUE THREAD

**Issue by AvdLee** [danger/swift#475]
This is the error I'm getting:
![image](https://user-images.githubusercontent.com/4329185/136974144-1230d79d-9504-48ab-a78c-6613868c75e1.png)

> Swift package target 'Danger' is linked as a static library by 'WeTransferPRLinterTests' and 'Danger', but cannot be built dynamically because there is a package product with the same name.

Using Xcode 13. The plugin is open-source, so you can try it out: 
https://github.com/WeTransfer/WeTransfer-iOS-CI/tree/master/WeTransferPRLinter

This is currently how the Package.swift looks:

```swift
// swift-tools-version:5.5
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "WeTransferPRLinter",
    products: [
        .library(
            name: "WeTransferPRLinter",
            targets: ["WeTransferPRLinter"]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/danger/swift", .exact("3.10.2")),
        .package(name: "DangerSwiftCoverage", url: "https://github.com/f-meloni/danger-swift-coverage", from: "1.1.0"),
        .package(name: "DangerXCodeSummary", url: "https://github.com/f-meloni/danger-swift-xcodesummary", from: "1.2.1"),
        .package(name: "Files", url: "https://github.com/JohnSundell/Files", from: "4.1.1")
    ],
    targets: [
        .target(
            name: "WeTransferPRLinter",
            dependencies: [
                .product(name: "Danger", package: "swift"),
                "DangerSwiftCoverage",
                "DangerXCodeSummary",
                "Files"
            ]
        ),
        .testTarget(
            name: "WeTransferPRLinterTests",
            dependencies: [
                "WeTransferPRLinter",
                .product(name: "DangerFixtures", package: "swift")
            ]
        )
    ]
)
```

Commenting out the test target lets Xcode build successfully.

**Comment by f-meloni** [comment]
> According to the old tags,
> 
> ```swift
> .library(name: "DangerDeps", type: .dynamic, targets: ["DangerDependencies"]),
> ```
> 
> should be commented out on release, as @AvdLee said.
> 
> https://github.com/danger/swift/blob/3.11.0/Package.swift https://github.com/danger/swift/blob/3.10.0/Package.swift

Yes, just realised that I've missed this change on https://github.com/danger/swift/pull/414

**Comment by AvdLee** [comment]
@f-meloni reopening this issue for the original issue description; I'm still getting this error for my plugin:

> Swift package target 'Danger' is linked as a static library by 'WeTransferPRLinterTests' and 'Danger', but cannot be built dynamically because there is a package product with the same name.

Don't you have the same for your plugins once you update it to Swift 5.5?
