### ISSUE TITLE
Getting DangerSwiftHammer error on all PRs

### ISSUE THREAD

**Issue by arpitdunzo** [danger/swift#487]
Command:
swift run danger-swift ci

Error:
'DangerSwiftHammer' /Users/distiller/project/.build/checkouts/DangerSwiftHammer: error: product dependency 'Danger' in package 'swift' not found

**Comment by theScud** [comment]
Fixed this was an issue with DangerSwiftHammer , fixed in the latest release @arpitdunzo close this :D

**Comment by arpitdunzo** [comment]
The above issue resolved by updating Danger Swift dependencies to the latest version. Hence closing the issue
