### ISSUE TITLE
Split Dangerfile.swift into multiple files

### ISSUE THREAD

**Issue by coonsama** [danger/swift#499]
is it possible to create multiple dangerfiles (or import scripts from another source files into dangerfile) without using plugins?
I have too many tests in my dangerfile and looking for a way to split them. How can this be done without a project/workspace? Or is there any way to use project/workspace instead of single dangerfile?

**Comment by 417-72KI** [comment]
You can use `// fileImport: filepath` to import script and extract variables or functions.
e.g. https://github.com/danger/swift/blob/master/Dangerfile.swift#L6

**Comment by coonsama** [comment]
This is exactly what I was looking for, thank you!
