### ISSUE TITLE
error: module compiled with Swift 5.5.2 cannot be imported by the Swift 5.6.1 compiler

### ISSUE THREAD

**Issue by antleung** [danger/swift#519]
Getting this error when running `danger-swift pr [path-to-pr]` locally

/var/folders/wf/mvxynpsj3wb3xk6v2bjmkqx80000gq/T/_tmp_dangerfile.swift:1:8: error: module compiled with Swift 5.5.2 cannot be imported by the Swift 5.6.1 compiler: /opt/homebrew/lib/danger/Danger.swiftmodule

Any idea on how to fix this?

**Comment by 417-72KI** [comment]
I think Danger-Swift is not supporting ABI/Module Stability.
It would be fixed with re-installing.

**Comment by antleung** [comment]
Thanks @417-72KI . Re-installing danger-swift fixed the issue.
