### ISSUE TITLE
[discussion] Drop Swift 5.3 support

### ISSUE THREAD

**Issue by 417-72KI** [danger/swift#523]
## Suggestion
- Make current version (`v3.12.3`) to be a last support for Swift 5.3
- Require Swift 5.4 for next release (`v3.12.4` or `v3.13.0`).
- Soon, create a new release ( `v3.12.5`, `v3.13.0` or `v3.13.1` ) and make it to require Swift 5.5.

## Motivation
There is an issue and workaround for building Danger-Swift in Swift 5.3 Docker image (https://github.com/danger/swift/issues/375, https://github.com/danger/swift/pull/426).

Fortunately, I tried to run `swift build --disable-sandbox -c release` in Swift 5.4 image and succeeded!
I think that supporting Swift 5.3 is no longer necessary.

Additionally, dropping Swift 5.4 is more happier for CI because
- Xcode 13.3 requires macOS monterey
- macOS monterey runner in GitHub Actions doesn't have Xcode 12.x (https://github.com/actions/virtual-environments/blob/main/images/macos/macos-12-Readme.md#xcode)
  - it means Swift 5.4 is not supported in macOS monterey runner.

**Comment by f-meloni** [comment]
Thank you for writing this issue :)
I'm totally OK with dropping Swift 5.3, and wait a little bit before dropping Swift 5.4, Ideally I would wait for the new Xcode major to come out and then drop that as well :)

**Comment by 417-72KI** [comment]
Thank you for reactions!
I will make a PR to prepare dropping 5.3 only 🚀
