### ISSUE TITLE
[Bug] Some times the danger ci fails in GitHub enterprise

### ISSUE THREAD

**Issue by MaatheusGois** [danger/swift#526]
![Captura de Tela 2022-06-17 às 13 41 44](https://user-images.githubusercontent.com/31082311/174341018-ebf4dc7c-0ef9-4922-ace6-800014dc458e.png)

**Comment by MaatheusGois** [comment]
Request failed [422]: https://github.pactual.net/api/v3/repos/bankingmobile/banking-ios-pix/pulls/314/reviews
Response: {
  "message": "Unprocessable Entity",
  "errors": [
    "Position is invalid"
  ],
  "documentation_url": "https://docs.github.com/enterprise/3.0/rest/reference/pulls#create-a-review-for-a-pull-request"
}
Feedback: https://github.pactual.net/bankingmobile/banking-ios-pix/pull/314#issuecomment-50072

**Comment by f-meloni** [comment]
It seems that is trying to post on an invalid line, what is your Dangerfile doing?

**Comment by Nikoloutsos** [comment]
@MaatheusGois 
This is not actually a bug. This is how github works.
In a GitHub PR you cannot comment in whatever line you want even from their webpage.

To illustrate it further you can comment here only in the lines inside the blue box.
![CleanShot 2022-09-02 at 13 08 45](https://user-images.githubusercontent.com/14034942/188117177-3776c4d3-fc1d-4f5c-8099-bd51342d243c.png)
