### ISSUE TITLE
Danger causing unexpected pipeline failures with concurrency enabled

### ISSUE THREAD

**Issue by squarefrog** [danger/swift#529]
We run iOS CI pipelines using `gitlab-runner` hosted on MacStudium Mac Minis. When two pipelines run at a similar time we get random failures resulting from our Danger step. Danger is setup as a nested Swift Package, which our CI server builds at the start of each pipeline run.

When the runner clones the repo, it clones to a folder using the runner concurrency identifier. For example, here are two possible folders:

```
/Users/[username]/builds/[runner-id]/0/[project-name]/.git/
/Users/[username]/builds/[runner-id]/1/[project-name]/.git/
```

For the most part this works great, however we are getting failures related to the temporary directory Danger uses. Looking at two failed pipelines, I can see while the clone paths are different, the danger temporary path is the same:

```
$ cd Danger && arch -x86_64 swift run danger-swift ci -i post_build -f --dangerfile DangerfilePostBuild.swift --cwd ../ && cd -
[1/1] Planning build
[0/0] Build complete!
<unknown>:0: error: error opening input file '/var/folders/rm/_fdw_5ys44xb_2gswdqh8c4r0000gq/T/_tmp_dangerfile.swift' (No such file or directory)
ERROR: Dangerfile eval failed at DangerfilePostBuild.swift
Failing the build, there is 1 fail.
```

```
$ cd Danger && arch -x86_64 swift run danger-swift ci -i post_build -f --dangerfile DangerfilePostBuild.swift --cwd ../ && cd -
[1/1] Planning build
[0/0] Build complete!
<unknown>:0: error: error opening input file '/var/folders/rm/_fdw_5ys44xb_2gswdqh8c4r0000gq/T/_tmp_dangerfile.swift' (No such file or directory)
ERROR: Dangerfile eval failed at DangerfilePostBuild.swift
Failing the build, there is 1 fail.
```

Is there a way for us to define the temporary directory to use with Danger? That way we could just nest a `.tmp` folder within the clone directory.

**Comment by squarefrog** [comment]
Created a PR for this.

**Comment by squarefrog** [comment]
Could I ask if this is likely to make it into a tagged release soon? We've tried to update our pipeline to use our fork in the meantime, but this has been a failure as we also use [Danger Xcode Summary](https://github.com/f-meloni/danger-swift-xcodesummary), which doesn't use the fork.

I've tried updating that too, but I then get `unexpectedCycle` errors from SPM. It doesn't seem like theres a nice way to use a fork right now.

**Comment by f-meloni** [comment]
Yes, I will make a release a soon as I come back from the holidays, if I manage to find a Mac even earlier 😁

**Comment by squarefrog** [comment]
Thank you, we appreciate it. Enjoy your well-earned rest 🌴

**Comment by f-meloni** [comment]
I've managed to get a Mac, and made a release (3.14.0).
Please let me know if everything is OK :)

**Comment by squarefrog** [comment]
That is fantastic news thank you! I’ll update our ci servers Monday and keep an eye on them throughout the week.
