### ISSUE TITLE
Please include a PR URL

### ISSUE THREAD

**Issue by DntPullALockett** [danger/swift#611]
I have Danger Swift implemented in a production project and also a test project. Implementation is exactly the same but for one it keeps failing that I need to include a PR URL even though one is given.

Danger Swift Version: 3.18.1

This is a private repo.

Not working:
`
swift run danger-swift pr https://github.com/rcg-digital-mobile/danger-swift-test/pull/1
Building for debugging...
[1/1] Write swift-version--58304C5D6DBC2206.txt
Build complete! (0.60s)
Please include a PR URL to run against
`

**Comment by orta** [comment]
you want `danger-swift ci` - the pr command is for testing against a specific pr

**Comment by DntPullALockett** [comment]
@orta  Yes I am testing this locally, not on a CI system
