### ISSUE TITLE
Support custom dangerfile

### ISSUE THREAD

**Issue by marcelofabri** [danger/swift#96]
Using `--dangerfile` would be great to split multiple setup into dangerfiles (e.g. one for PR validation and one that needs build results)

This is supported on danger-js and danger-ruby already.

**Comment by orta** [comment]
Makes sense, yeah

**Comment by f-meloni** [comment]
@orta Is it possible to pass the Dangerfile's custom path, if any, on the danger DSL settings object? (Given the parameter `dangerfile` is passed to `danger-js` in any case when you call `danger-swift ci`, `local` or`pr`)
Given the current main implementation I would rather receive it on the JSON than as parameter 
Does it looks a good approach to you?

**Comment by orta** [comment]
Yeah, I think that's a real good thing to do  - it might get a bit tricky with the commands like `danger-swift ci` which will need documenting as supporting them too, and right now danger-js will validate that the args passed are pre-defined (and will bail if it isn't supported, this can be turned off though) 

👍

**Comment by orta** [comment]
Fixed by #100
